---
name: Lingua-HE-MacHebrew
abstract: 'transcoding between Mac OS Hebrew encoding and Unicode'
version: 0.10
author:
  - 'SADAHIRO Tomoyuki <SADAHIRO@cpan.org>'
license: perl
distribution_type: module
requires:
  bytes: 0
  DynaLoader: 0
  Exporter: 0
  strict: 0
  warnings: 0
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 0
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
generated_by: 'ExtUtils::MakeMaker version 6.57_05'
